<?php
$profiles = [
  'sebastian-vaca' => ['player'=>1,'name'=>'Sebastian Vaca','status'=>'Adicto a tus ojos','power'=>'Social, divertido y extrovertido','skill'=>'Gamer de Temu: juega barato, pero celebra como profesional','strengths'=>'Hace amigos hasta en la fila del bar y convierte cualquier reunión en una aventura.','weaknesses'=>'Miedo legendario a la chamba, las mujeres y que se acabe el alcohol.','attacks'=>'Invitación a la chuma · Coqueteo con lag · Desaparición cuando toca trabajar','color'=>'#ff3038','rgb'=>'255,48,56'],
  'gabriel-rojas' => ['player'=>2,'name'=>'Gabriel Rojas','status'=>'Con novia (buff emocional activo)','power'=>'INQUEBRANTABLE: Puede reprobar, repetir materias, perder dignidad académica y aun así volver al siguiente semestre como si nada hubiera pasado. Nunca abandona la partida.','skill'=>'SUERTE MILAGROSA: Acumula toda la suerte del semestre para gastarla en UNA sola prueba final. Probabilidad de activación: 2%. Cuando activa: “No estudié nada, pero justo preguntaron lo único que sabía.”','strengths'=>'Consejo de guerra interno: cuando está a punto de rendirse, su cerebro convoca una reunión de emergencia y alguien grita: “YA LLEGAMOS HASTA AQUÍ, HP.” · Insomnio II: reduce la necesidad percibida de dormir en 35%, pero aumenta las probabilidades de confundir Java con JavaScript. · Resistencia al fracaso +75: después del tercer cero ya desarrolla inmunidad emocional.','weaknesses'=>'Procrastinación: +300% de productividad exactamente 4 horas antes de entregar. · TDAH modo pestañas: empieza haciendo la tarea, abre YouTube, busca un tutorial y termina viendo “10 misterios del océano que la ciencia no puede explicar”. · “Todavía hay tiempo”: efecto pasivo activo hasta las 11:47 p. m.','attacks'=>'CTRL + C / CTRL + V: copia conocimiento ancestral de fuentes desconocidas; daño crítico si el profesor no revisa el historial. · PARRY: “Pero profe, en el enunciado no decía eso”; 15% de posibilidad de bloquear una corrección. · TANQUEAR CEROS: recibe un 0/10 sin retroceder ni un centímetro. · ULTIMATE: “¿CUÁNTO NECESITO EN EL FINAL?” Invoca la calculadora y descubre que necesita 11.8/10 para aprobar. 💀','color'=>'#289cff','rgb'=>'40,156,255','details'=>[
    'Nombre'=>'Gabriel Rojas',
    'Clase'=>'Estudiante Legendario de Supervivencia Académica',
    'Estado civil'=>'Con novia (buff emocional activo)',
    'Poder principal — INQUEBRANTABLE'=>'Puede reprobar, repetir materias, perder dignidad académica y aun así volver al siguiente semestre como si nada hubiera pasado. Nunca abandona la partida.',
    'Habilidad definitiva — SUERTE MILAGROSA'=>'Acumula toda la suerte del semestre para gastarla en UNA sola prueba final. Probabilidad de activación: 2%. Cuando activa: “No estudié nada, pero justo preguntaron lo único que sabía.”',
    'Fortalezas'=>'Consejo de guerra interno: cuando está a punto de rendirse, su cerebro convoca una reunión de emergencia y alguien grita: “YA LLEGAMOS HASTA AQUÍ, HP.” · Insomnio II: reduce la necesidad percibida de dormir en 35%, pero aumenta las probabilidades de confundir Java con JavaScript. · Resistencia al fracaso +75: después del tercer cero ya desarrolla inmunidad emocional.',
    'Debilidades'=>'Procrastinación: +300% de productividad exactamente 4 horas antes de entregar. · TDAH modo pestañas: empieza haciendo la tarea, abre YouTube, busca un tutorial y termina viendo “10 misterios del océano que la ciencia no puede explicar”. · “Todavía hay tiempo”: efecto pasivo activo hasta las 11:47 p. m.',
    'Ataques'=>'CTRL + C / CTRL + V: copia conocimiento ancestral de fuentes desconocidas; daño crítico si el profesor no revisa el historial. · PARRY: “Pero profe, en el enunciado no decía eso”; 15% de posibilidad de bloquear una corrección. · TANQUEAR CEROS: recibe un 0/10 sin retroceder ni un centímetro. · ULTIMATE: “¿CUÁNTO NECESITO EN EL FINAL?” Invoca la calculadora y descubre que necesita 11.8/10 para aprobar. 💀',
    'Frase legendaria'=>'“Mientras matemáticamente exista una posibilidad, todavía se puede.”',
    'Rareza'=>'⭐⭐⭐⭐⭐ MITOLÓGICO',
    'Probabilidad de graduarse'=>'Estadísticamente cuestionable, espiritualmente inevitable.'
  ]],
  'bryan-yepez' => ['player'=>3,'name'=>'Bryan Yepez','nameDetail'=>'Bryan Yepez — Personaje desbloqueado, estadísticas cuestionables.','status'=>'Soltero en matchmaking — Buscando dúo permanente, aunque el servidor nunca conecta. 🎮💀','power'=>'Alcoholismo en proceso — +10 de confianza, -20 de coordinación. 🍻','skill'=>'Modo Tryhard — Se activa automáticamente cuando alguien dice “no puedes ganar”.','strengths'=>'Gaming, dormir hasta tarde, comer como si tuviera regeneración infinita, sobrevivir a cualquier party y apostar como si supiera lo que está haciendo. 🎰','weaknesses'=>'La ex 💔 · Ingeniería 💀 · Alcohol 🍻 · Hambre · Sueño · Y el clásico “una última partida”.','attacks'=>'Rage Quit · Headshot · Combo Borracho · Clutch Milagroso · “Ya fue, otra partida” · All-in emocional 💀','color'=>'#ffd52e','rgb'=>'255,213,46'],
  'vladimir-gonzales' => ['player'=>4,'name'=>'Vladimir Moposita','status'=>'En modo Survival (y corriendo con medio corazón)','power'=>'Multiplicación milagrosa de memoria RAM (para que el Minecraft con 200 mods no queme la casa)','skill'=>'Aprobar las pruebas de inglés a base de pura intuición y criar Pokémon perfectos','strengths'=>'Paciencia infinita para convencer a la PC de que todavía no es hora de rendirse','weaknesses'=>'Distraerse optimizando juegos en vez de terminar los proyectos de la universidad','attacks'=>'CTRL+Z DESESPERADO · CONSTRUCCIÓN DE CHOZA DE TIERRA DE EMERGENCIA · LLANTO TÁCTICO PORQUE EL CÓDIGO NO COMPILA','color'=>'#69f02c','rgb'=>'105,240,44'],
  'andrew-lara' => ['player'=>5,'name'=>'Andrew Lara','nameDetail'=>'Andrew Johan Lara Fernández — Desarrollador en entrenamiento, sobreviviente de bugs y entregas de último minuto.','status'=>'Modo independiente — Actualmente en una relación seria con el código y los proyectos que “solo necesitan un último cambio”. 💻','power'=>'Lógica Adaptativa — Convierte problemas confusos en soluciones… después de unos cuantos console.log().','skill'=>'Modo Debug — Cuando todo deja de funcionar, aumenta misteriosamente su capacidad de encontrar el error.','strengths'=>'Resolución de problemas, aprendizaje rápido, creatividad, persistencia y una peligrosa confianza en que “sí alcanza el tiempo”.','weaknesses'=>'Errores que aparecen sin razón, documentación inexistente, conflictos de Git y decir “ya casi termino” demasiado pronto.','attacks'=>'Debug Crítico · Consulta SQL · Git Push · API Definitiva · Ctrl + Z de Emergencia · Deploy sin Miedo','color'=>'#ae42ff','rgb'=>'174,66,255'],
  'sebastian-freire' => ['player'=>6,'name'=>'Sebastian Freire','nameDetail'=>'Sebastian Alexander Freire Ortega','status'=>'En una relación de amor/odio con los horarios de la universidad y el trabajo de medio tiempo.','power'=>'Estamina Inagotable — Capaz de encadenar clases, una jornada laboral de 4 horas y una sesión demoledora de gym sin vaciar su barra de energía.','skill'=>'Invocación del Focus Mode mediante la playlist perfecta de Chase Atlantic para silenciar el mundo mientras maqueta tareas estadísticas avanzadas en Overleaf.','strengths'=>'Build clase Tanque forjada con rutinas de gym, universidad y pruebas; paciencia extrema para administrar servidores de Minecraft Java modeados y afinidad natural para invocar gatos y perros pequeños.','weaknesses'=>'Procrastinación y ataques de TDAH.','attacks'=>'Dominio de Estamina: energía ilimitada durante 5 minutos para rendir exámenes sin dormir · Ctrl + C / Ctrl + V · Parry · Tanquear Exámenes','color'=>'#ff6a1f','rgb'=>'255,106,31'],
];
$key = $profileKey ?? '';
if (!isset($profiles[$key])) { http_response_code(404); exit('Perfil no encontrado'); }
$p = $profiles[$key];
$magicObjects = [
  'sebastian-vaca' => [['image'=>'magic-objects/pala.png','name'=>'Pala Mágica','effect'=>'PERMITE AL USUARIO CHAMBEAR Y CONSEGUIR DINERO.'],['image'=>'magic-objects/tridente-matricular.png','name'=>'Tridente Matricular','effect'=>'SI EL PERSONAJE TE GOLPEA CON ESTA ARMA PIRDES LA MATRICULA ACTUAL.'],['image'=>'magic-objects/propuesta-trabajo.png','name'=>'Propuesta de Trabajo','effect'=>'TE OBLICA A TRABAJAR BAJO PRESION 18 HORAS Y CON EXPLOTACION LABORAL.']],
  'gabriel-rojas' => [['image'=>'magic-objects/reloj-del-tiempo.png','name'=>'Reloj del Tiempo','effect'=>'Al usarlo da un tiempo extra para llegar a clases.'],['image'=>'magic-objects/enchiridion.jpg','name'=>'Enchiridion','effect'=>'Guarda toda la información obtenida en el semestre para la segunda matrícula.'],['image'=>'magic-objects/mal-presagio.png','name'=>'Mal Presagio','effect'=>'Este hechizo hace que los ingenieros te agarren pique.']],
  'bryan-yepez' => [['image'=>'magic-objects/estrella-wither.png','pixel'=>true,'name'=>'Estrella Wither','effect'=>'Te guía en la carrera cuando te sientes perdido.'],['image'=>'magic-objects/allay.png','pixel'=>true,'name'=>'Allay','effect'=>'Te vuelve invisible para fugarte de clases e ir a tomar.'],['image'=>'magic-objects/pulpito.png','pixel'=>true,'name'=>'Pulpito','effect'=>'Te agrega brazos extra para hacer todo el trabajo cuando tu equipo no te ayuda.']],
  'vladimir-gonzales' => [['image'=>'magic-objects/bielita.png','pixel'=>true,'name'=>'Bielita','effect'=>'Un traguito para ahogar las penas.'],['image'=>'magic-objects/catalejo.png','pixel'=>true,'name'=>'Catalejo','effect'=>'Mejora la visión para poder copiar mejor en los exámenes.'],['image'=>'magic-objects/peruanito.png','pixel'=>true,'name'=>'Peruanito','effect'=>'Invoca un ceviche legendario que recupera energía y te salva del hambre entre clases.']],
  'andrew-lara' => [['image'=>'magic-objects/llave-del-demonio.png','pixel'=>true,'name'=>'Llave del Demonio','effect'=>'Abre el depa del foráneo para reuniones y chumas.'],['image'=>'magic-objects/totem-inmortalidad.png','pixel'=>true,'name'=>'Tótem de la Inmortalidad','effect'=>'Te da los puntos que te faltan para no perder el semestre.'],['image'=>'magic-objects/brawl-stone.png','pixel'=>true,'name'=>'Brawl Stone','effect'=>'Instala Brawl Stars en tu celular para matar el aburrimiento.']],
  'sebastian-freire' => [['image'=>'magic-objects/nucleo-central.png','pixel'=>true,'name'=>'Núcleo Central','effect'=>'Mantiene centrado y unido a su equipo de trabajo.'],['image'=>'magic-objects/negrito.png','pixel'=>true,'name'=>'Negrito','effect'=>'Habilidad para aparecer de la nada con voz demoníaca.'],['image'=>'magic-objects/foco.png','pixel'=>true,'name'=>'Foco','effect'=>'Fortalece la colaboración en el equipo añadiendo más inteligencia a cada integrante.']],
];
$profileMusic = [
  'sebastian-vaca' => '../assets/music-sebastian-vaca.mp3',
  'gabriel-rojas' => '../assets/music-gabriel-rojas.mp3',
  'bryan-yepez' => '../assets/music-bryan-yepez.mp3',
  'vladimir-gonzales' => '../assets/music-vladimir-moposita.mp3',
  'andrew-lara' => '../assets/music-andrew-lara.mp3',
  'sebastian-freire' => '../assets/music-sebastian-freire.mp3',
];
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= htmlspecialchars($p['name']) ?> | Perfil</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700;900&family=Cinzel:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="../perfil.css"><link rel="stylesheet" href="../perfil-theme.css"><link rel="stylesheet" href="../perfil-scroll-fix.css"><link rel="stylesheet" href="../perfil-game.css"></head>
<script>document.documentElement.style.setProperty('--accent','<?= $p['color'] ?>');document.documentElement.style.setProperty('--accent-rgb','<?= $p['rgb'] ?>');</script>
<body data-profile-music="<?= htmlspecialchars($profileMusic[$key] ?? '') ?>"><link rel="stylesheet" href="../perfil-button.css"><link rel="stylesheet" href="../perfil-stats-gaming.css"><link rel="stylesheet" href="../perfil-music.css"><script defer src="../perfil-button.js"></script><script defer src="../perfil-music.js"></script>
<header><a class="back-team" href="../equipo.php">Volver al equipo</a><div class="profile-header-actions"><span>P<?= $p['player'] ?> / Perfil</span><button class="profile-settings-button" type="button" aria-label="Configuración de música" title="Configuración de música">⚙</button></div></header>
<main>
 <section class="profile-hero"><div><p class="kicker">Jugador <?= $p['player'] ?> seleccionado</p><h1><?= htmlspecialchars($p['name']) ?></h1><p class="intro">Ficha oficial del personaje, habilidades y atributos de combate.</p></div><img src="<?= $key === 'gabriel-rojas' ? 'assets/foto.jpg' : '../assets/creador-'.str_pad((string)$p['player'], 2, '0', STR_PAD_LEFT).'.png' ?>" alt="<?= htmlspecialchars($p['name']) ?>"></section>
 <section class="details"><p class="kicker">Detalles</p><h2>Información del personaje</h2><div class="stats">
  <?php if (isset($p['details'])): foreach ($p['details'] as $label => $value): ?>
  <article class="<?= in_array($label, ['Poder principal — INQUEBRANTABLE','Habilidad definitiva — SUERTE MILAGROSA','Fortalezas','Debilidades','Ataques','Frase legendaria'], true) ? 'wide' : '' ?>"><span><?= htmlspecialchars($label) ?></span><strong><?= htmlspecialchars($value) ?></strong></article>
  <?php endforeach; else: ?>
  <article><span>Nombre y apellido</span><strong><?= htmlspecialchars($p['nameDetail'] ?? $p['name']) ?></strong></article>
  <article><span>Estado civil</span><div class="private-value"><strong><?= htmlspecialchars($p['status']) ?></strong><button class="eye" type="button" aria-label="Ver formulario de tarjeta">◉</button></div></article>
  <article><span>Poder</span><strong><?= htmlspecialchars($p['power']) ?></strong></article>
  <article><span>Habilidad especial</span><strong><?= htmlspecialchars($p['skill']) ?></strong></article>
  <article><span>Fortalezas</span><strong><?= htmlspecialchars($p['strengths']) ?></strong></article>
  <article><span>Debilidades</span><strong><?= htmlspecialchars($p['weaknesses']) ?></strong></article>
  <article class="wide"><span>Ataques</span><strong><?= htmlspecialchars($p['attacks']) ?></strong></article>
  <?php endif; ?>
 </div></section>
 <style>.magic-objects{padding:70px 0}.magic-objects h2{margin:8px 0 30px;font:700 clamp(2rem,5vw,4rem) "Cinzel Decorative",serif}.magic-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.magic-card{min-height:210px;padding:26px;border:1px solid rgba(var(--accent-rgb),.55);border-radius:18px;background:linear-gradient(145deg,rgba(var(--accent-rgb),.13),rgba(3,18,12,.9));box-shadow:inset 0 0 24px rgba(var(--accent-rgb),.08),0 12px 28px rgba(0,0,0,.25);transition:.25s}.magic-card:hover{transform:translateY(-5px);border-color:var(--accent);box-shadow:0 0 25px rgba(var(--accent-rgb),.25)}.magic-icon{display:grid;width:74px;height:74px;margin-bottom:24px;place-items:center;border:1px solid rgba(var(--accent-rgb),.7);border-radius:16px;background:rgba(var(--accent-rgb),.12);box-shadow:0 0 18px rgba(var(--accent-rgb),.25);font-size:1.75rem}.magic-icon img{display:block;width:100%;height:100%;padding:7px;object-fit:contain;border-radius:12px}.magic-icon--document{width:92px;height:112px}.magic-card h3{margin:0 0 10px;color:#fff;font:700 1.05rem "Cinzel Decorative",serif}.magic-card p{margin:0;color:#bdc5c1;font-size:.82rem;line-height:1.65}@media(max-width:720px){.magic-grid{grid-template-columns:1fr}.magic-card{min-height:0}}</style>
 <style>.magic-card{overflow:hidden;min-width:0}.magic-card>div{min-width:0}.magic-card h3,.magic-card p{overflow-wrap:anywhere}.magic-icon{flex:0 0 auto;overflow:hidden;max-width:100%}.magic-icon img{max-width:100%;max-height:100%}.magic-icon--enchiridion{width:82px;height:112px;padding:5px}.magic-icon--enchiridion img{padding:0;object-fit:contain;border-radius:8px}@media(max-width:480px){.magic-card{padding:20px}.magic-icon--enchiridion{width:72px;height:98px}}</style>
 <style>.magic-icon--pixel img{padding:12px;object-fit:contain;image-rendering:pixelated;image-rendering:crisp-edges;transform:scale(1.35)}</style>
 <section class="magic-objects" aria-labelledby="magic-title"><p class="kicker">Inventario del personaje</p><h2 id="magic-title">Objetos mágicos</h2><div class="magic-grid">
 <?php foreach ($magicObjects[$key] as $object): ?>
  <?php $objectClass = isset($object['image']) && str_contains($object['image'], 'propuesta') ? ' magic-icon--document' : (isset($object['image']) && str_contains($object['image'], 'enchiridion') ? ' magic-icon--enchiridion' : (!empty($object['pixel']) ? ' magic-icon--pixel' : '')); ?>
  <article class="magic-card"><span class="magic-icon<?= $objectClass ?>" aria-hidden="true"><?php if (isset($object['image'])): ?><img src="<?= htmlspecialchars($object['image']) ?>" alt=""><?php else: ?><?= $object['icon'] ?><?php endif; ?></span><div><h3><?= htmlspecialchars($object['name']) ?></h3><p><?= htmlspecialchars($object['effect']) ?></p></div></article>
 <?php endforeach; ?>
 </div></section>
 <?php if ($key === 'sebastian-vaca'): ?>
 <section class="game-slot game-slot--active" id="medieval-legend">
  <div class="game-heading"><div><p class="kicker">Juego de Sebasti&aacute;n Vaca</p><h2>Medieval Legend</h2><p class="game-description">Convi&eacute;rtete en el &uacute;ltimo guardi&aacute;n y sobrevive a la leyenda. Usa WASD para moverte, ESPACIO para atacar y ESC para abrir las mejoras.</p></div><a class="game-open" href="medieval-legend/index.html" target="_blank" rel="noopener">Abrir en pantalla completa</a></div>
  <div class="game-embed"><iframe src="medieval-legend/index.html" title="Jugar Medieval Legend" loading="lazy" allow="fullscreen" allowfullscreen></iframe></div>
 </section>
 <?php elseif ($key === 'gabriel-rojas'): ?>
 <section class="game-slot game-slot--active" id="corre-que-te-atrasas">
  <div class="game-heading"><div><p class="kicker">Juego de Gabriel Rojas</p><h2>Corre que te atrasas</h2><p class="game-description">El camino “fácil” nunca es fácil. Llega a la facultad superando trampas y plataformas a lo largo de tres niveles. Muévete con A/D o las flechas y salta con W, ESPACIO o flecha arriba.</p></div><a class="game-open" href="game/index.html" target="_blank" rel="noopener">Abrir en pantalla completa</a></div>
 <div class="game-embed"><iframe src="game/index.html" title="Jugar Corre que te atrasas" loading="lazy" allow="fullscreen" allowfullscreen></iframe></div>
 </section>
 <?php elseif ($key === 'bryan-yepez'): ?>
 <section class="game-slot game-slot--active" id="neon-maze-adventure">
  <div class="game-heading"><div><p class="kicker">Juego de Bryan Y&eacute;pez</p><h2>Neon Maze Adventure</h2><p class="game-description">Escapa del laberinto de ne&oacute;n a trav&eacute;s de tres niveles. Recoge puntos y objetos especiales, evita trampas y centinelas, y alcanza la puerta de salida. Usa WASD o las flechas; tambi&eacute;n incluye controles t&aacute;ctiles.</p></div><a class="game-open" href="neon-maze/juego.html" target="_blank" rel="noopener">Abrir en pantalla completa</a></div>
 <div class="game-embed"><iframe src="neon-maze/juego.html" title="Jugar Neon Maze Adventure" loading="lazy" allow="fullscreen" allowfullscreen></iframe></div>
 </section>
 <?php elseif ($key === 'vladimir-gonzales'): ?>
 <section class="game-slot game-slot--active" id="carrera-interminable">
  <div class="game-heading"><div><p class="kicker">Juego de Vladimir Moposita</p><h2>Carrera Interminable</h2><p class="game-description">Elige tu auto y sobrevive al tr&aacute;fico de una pista sin fin. Cambia entre tres carriles, evita los autos rivales y consigue el mejor r&eacute;cord usando las flechas izquierda y derecha o los controles t&aacute;ctiles.</p></div><a class="game-open" href="carrera-interminable/index.php" target="_blank" rel="noopener">Abrir en pantalla completa</a></div>
  <div class="game-embed game-embed--portrait"><iframe src="carrera-interminable/index.php" title="Jugar Carrera Interminable" loading="lazy" allow="fullscreen" allowfullscreen></iframe></div>
 </section>
 <?php elseif ($key === 'andrew-lara'): ?>
 <section class="game-slot game-slot--active andrew-game-access" id="andrew-game">
  <div class="game-heading"><div><p class="kicker">Juego de Andrew Lara</p><h2>Aventura Mística</h2><p class="game-description">Explora un mundo fantástico, descubre sus secretos y entra directamente a la aventura.</p></div></div>
  <div class="andrew-game-cover"><img src="../assets/andrew-game-cover.png" alt="Vista previa del juego de Andrew Lara"><span class="andrew-cover-shade" aria-hidden="true"></span><a class="andrew-enter-game" href="https://protecting-examines-essential-assume.trycloudflare.com/" target="_blank" rel="noopener noreferrer"><span>Entrar</span></a></div>
 </section>
 <?php elseif ($key === 'sebastian-freire'): ?>
 <section class="game-slot game-slot--active" id="pong-retro">
  <div class="game-heading"><div><p class="kicker">Juego de Sebasti&aacute;n Freire</p><h2>Pong Retro</h2><p class="game-description">Enfr&eacute;ntate a la CPU en un duelo de tenis arcade. Mu&eacute;vete con W/S o las flechas, usa ESPACIO para pausar y ESC para reiniciar el marcador. El primero en llegar a 7 gana.</p></div><a class="game-open" href="pong-retro/index.html" target="_blank" rel="noopener">Abrir en pantalla completa</a></div>
  <div class="game-embed"><iframe src="pong-retro/index.html" title="Jugar Pong Retro" loading="lazy" allow="fullscreen; autoplay" allowfullscreen></iframe></div>
 </section>
 <?php else: ?>
 <section class="game-slot"><p class="kicker">Próximamente</p><h2>Zona de juego</h2><div><span>GAME SLOT</span><p>Espacio reservado para agregar el juego de este personaje.</p></div></section>
 <?php endif; ?>
</main>
<div class="modal" aria-hidden="true"><section class="card-panel" role="dialog" aria-modal="true" aria-labelledby="card-title"><button class="close" type="button" aria-label="Cerrar">×</button><p class="kicker">Acceso privado</p><h2 id="card-title">Ingresar tarjeta</h2><p class="safe-note">Formulario visual de demostración. Los datos no se envían ni se almacenan.</p><form autocomplete="off" data-lpignore="true" data-1p-ignore><label>Número de tarjeta<input name="demo_card_number" inputmode="numeric" autocomplete="off" data-lpignore="true" placeholder="0000 0000 0000 0000" maxlength="19"></label><div class="form-row"><label>Vencimiento<input name="demo_expiry" autocomplete="off" data-lpignore="true" placeholder="MM/AA" maxlength="5"></label><label>CVV<input name="demo_security_code" type="password" inputmode="numeric" autocomplete="new-password" data-lpignore="true" placeholder="000" maxlength="4"></label></div><label>Titular de la tarjeta<input name="demo_holder" autocomplete="off" data-lpignore="true" placeholder="NOMBRE COMPLETO"></label><label>Dirección<input name="demo_address" autocomplete="off" data-lpignore="true" placeholder="Dirección"></label><div class="form-row"><label>Ciudad<input name="demo_city" autocomplete="off" data-lpignore="true" placeholder="Ciudad"></label><label>Código postal<input name="demo_postal" inputmode="numeric" autocomplete="off" data-lpignore="true" placeholder="00000"></label></div><button class="submit" type="submit">Ingresar</button></form></section></div>
<script src="../perfil.js"></script><script src="../perfil-theme.js"></script><script>const demoForm=document.querySelector('.card-panel form');const clearDemoForm=()=>{demoForm.reset();demoForm.querySelectorAll('input').forEach(input=>{input.value='';input.setAttribute('value','')})};clearDemoForm();const profileEye=document.querySelector('.eye');if(profileEye){profileEye.addEventListener('click',()=>{clearDemoForm();const panel=document.querySelector('.card-panel');panel.scrollTop=0;document.querySelector('.card-panel input').focus({preventScroll:true})})}document.querySelector('.close').addEventListener('click',clearDemoForm);window.addEventListener('pageshow',clearDemoForm);</script></body></html>
